marks=[]
f1=int(input("Enter the marks :"))
marks.append(f1)
f2=int(input("Enter the marks 2:"))
marks.append(f2)
f3=int(input("Enter the marks 3:"))
marks.append(f3)
f4=int(input("Enter the marks 4:"))
marks.append(f4)
f5=int(input("Enter the marks 5:"))
marks.append(f5)
f6=int(input("Enter the marks 6:"))
marks.append(f6)
f7=int(input("Enter the marks 7:"))
marks.append(f7)
marks.sort()
print(marks)

